"""empty message

Revision ID: 00def19e141c
Revises: a33129a11ae3
Create Date: 2018-01-24 20:41:33.667856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00def19e141c'
down_revision = 'a33129a11ae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translated_product', sa.Column('aa_seq', sa.String(length=100000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translated_product', 'aa_seq')
    # ### end Alembic commands ###
