"""empty message

Revision ID: 215bac16883e
Revises: 53ebbc0d1424
Create Date: 2018-02-02 08:56:46.915370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215bac16883e'
down_revision = '53ebbc0d1424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SampleDate')
    op.drop_table('AminoAcidSeq')
    op.drop_table('Tissue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tissue',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Tissue_id_seq"\'::regclass)'), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Tissue_pkey')
    )
    op.create_table('AminoAcidSeq',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"AminoAcidSeq_id_seq"\'::regclass)'), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='AminoAcidSeq_pkey')
    )
    op.create_table('SampleDate',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"SampleDate_id_seq"\'::regclass)'), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='SampleDate_pkey')
    )
    # ### end Alembic commands ###
