"""empty message

Revision ID: 2b379d1715f6
Revises: fea745f662a4
Create Date: 2018-01-22 23:06:43.290044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b379d1715f6'
down_revision = 'fea745f662a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('families', sa.Column('rep_class_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'families', 'classes', ['rep_class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'families', type_='foreignkey')
    op.drop_column('families', 'rep_class_id')
    # ### end Alembic commands ###
