"""empty message

Revision ID: e5713ad570ce
Revises: 
Create Date: 2018-02-07 02:37:14.548565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5713ad570ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_id'), 'classes', ['id'], unique=False)
    op.create_table('families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('rep_class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rep_class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_families_id'), 'families', ['id'], unique=False)
    op.create_table('reps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('rep_family_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rep_family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reps_id'), 'reps', ['id'], unique=False)
    op.create_table('information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('sw_score', sa.Integer(), nullable=True),
    sa.Column('mili_div', sa.Integer(), nullable=True),
    sa.Column('mili_del', sa.Integer(), nullable=True),
    sa.Column('mili_ins', sa.Integer(), nullable=True),
    sa.Column('geno_name', sa.String(length=100), nullable=True),
    sa.Column('geno_start', sa.Integer(), nullable=True),
    sa.Column('geno_end', sa.Integer(), nullable=True),
    sa.Column('geno_left', sa.Integer(), nullable=True),
    sa.Column('rep_start', sa.Integer(), nullable=True),
    sa.Column('rep_end', sa.Integer(), nullable=True),
    sa.Column('rep_left', sa.Integer(), nullable=True),
    sa.Column('dna_seq', sa.Text(), nullable=True),
    sa.Column('aa_seq', sa.Text(), nullable=True),
    sa.Column('rep_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rep_id'], ['reps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('information')
    op.drop_index(op.f('ix_reps_id'), table_name='reps')
    op.drop_table('reps')
    op.drop_index(op.f('ix_families_id'), table_name='families')
    op.drop_table('families')
    op.drop_index(op.f('ix_classes_id'), table_name='classes')
    op.drop_table('classes')
    # ### end Alembic commands ###
